### PR TITLE
fix(scraper): allow printing multiple locations

### LINKED ISSUE #409: artv3033 location
Room was listed incorrectly

Category: Issue
Contact: u6080485@anu.edu.au

_Originally submitted via the Microsoft Form_

### PR DESCRIPTION
**Pull request by jthvai**
Fixes #409

Since we have no way of testing the scraper except in prod, @pl4nty I'd like you to take a look at this before merging.

~~Also, please wait for [this Scrape](https://github.com/pl4nty/anutimetable/actions/runs/7968064010) to finish first since I want to make sure my linting changes are fine~~ ok we good

### CODE REVIEW

**Comment by jthvai** [comment]
(cancelled the build + deploy workflow since I didn't modify anything there)

**Comment by jthvai** [comment]
Ruh roh who didn't escape their strings properly

**Comment by jthvai** [comment]
51bc667 introduced a new issue that still needs to be addressed before merging:

The Choose/Reset button now often gets pushed out of view, particularly in cases like MUSI1101 2023 S1 where the location is "Peter Karmel 1.31; Peter Karmel Big Band Room; Peter Karmel Foster Room; Peter Karmel 1.17 Small Ensemble; Peter Karmel 1.28; Peter Karmel 1.32"

**Comment by jthvai** [comment]
I've FFed 38b9326 for now so that people can at least inspect the HTML to get the full location string if they want

**Comment by pl4nty** [comment]
I suspect this was implemented to fix cases like MUSI1101 2023 S1, is there anything else we could try?

**Comment by jthvai** [comment]
Relegated to rewrite.

**Pull request closed without merging**
